{% set name = "seabird" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f5902a3e795946f09e711a02e0b2dcc7efa782d5238cab5de2e2858d72af27aa

build:
  number: 1
  entry_points:
    - seabird=seabird.cli:cli
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - click >=6.6
    - numpy >=1.14
    - setuptools >=49.1
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - seabird
  commands:
    - seabird --help

about:
  home: http://seabird.castelao.net
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Parser for Sea-Bird's CTD and TSG.
  doc_url: https://seabird.readthedocs.io/en/latest/
  dev_url: https://github.com/castelao/seabird

extra:
  recipe-maintainers:
    - castelao
